# Generated by Django 4.2.16 on 2024-11-29 23:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous_question', '0002_delete_testlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='Anonymous_question.test')),
            ],
        ),
    ]
