# Generated by Django 4.2.16 on 2024-12-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_link', '0001_initial'),
        ('test_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlink',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='test_management.test'),
        ),
    ]
